---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# my-first-repository

<!-- badges: start -->
<!-- badges: end -->

This is my first repository. 

---
title: "My Research Interest"
author: "Mariana Buitrago, __buitragm@mcmaster.ca__"
date: "2024-09-13"
output: html_document
---

# Metabolomics and nutrition 

Finding biomarkers of **Omega-3** intake in serum and urine as a path to determine if it's possible to relate this diet biomarker with cardiovascular diseases risk. The analytical technique I will employ will be LC (liquid chromatography) coupled to mass spectrometry for samples from a randomized clinical trial.

# Favorites

## Favorite Music:

1. Te aviso, te anuncio - _Shakira_ 
2. Oh Qué Será - _Willie Colón_
3. De Mí Enamórate - _Juan Gabriel_ 
4. August - _Taylor Swift_
5. Gracia Divina - _Celia Cruz_

## Favorite Equation:

My favorite equation is the photosynthesis chemical equation:


$$
6CO_2 + 6H_2O\frac{light}{chlorophyll}C_6H_{12}O_6+6O_2
$$

## Favorite artists:

**Name** | **Achievements** |
- | - |
Gustav Klimt | Prestigious representative of the modernist movement of the Viennese Secession. _Favorite work: Flower Garden_
Hector Berlioz | French Romantic composer and conductor who fought against his father to be able to follow his dreams. _Favorite work: Symphonie fantastique_
Gustav Holst | His orchestral suite The Planets is an amazing piece of art. _Favorite work: The Planets, Op. 32:I. Mars, the Bringer of War_
Charles Baudelaire | Included among the _cursed poets of France_ in the 19th century. _Favorite work: The clock_ 
Violeta Parra | Leading folklorists in South America and promoter of popular music in her country, Chile. _Favorite work: Qué he sacado con quererte_ 

# A Chunk of Code

``` r
y = expected cost
x = inflation %
a = initial cost

$$
y = ax+a
$$
```

## Git 

This repository now is set up for git. 

## Github 

I also set up bla bla bla 
